import { Inter } from "next/font/google";
import "../styles/globals.css";
import Navbar from "../app/components/Navbar";
import Filter from "../app/components/Filter";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Filter />

        {children}
      </body>
    </html>
  );
}
