import { Inter } from "next/font/google";
import "../styles/globals.css";
import Filter from "./components/Filter";
import AuthProvider from "./components/AuthProvider";
import Navbar from "./components/Navbar";
import { CartProvider } from "@/contexts/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <CartProvider>
          <Navbar />
          <Filter />
          {children}
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
